service: auth-server

frameworkVersion: '2'

provider:
    name: aws
    runtime: nodejs12.x
    region: us-east-1
    timeout: 60
    environment:
        CLIENT_ID: ${file(config.json):CLIENT_ID}
        CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
        PROJECT_ID: ${file(config.json):PROJECT_ID}
        CALENDAR_ID: ${file(config.json):CALENDAR_ID}

functions:
    getAuthURL:
        handler: handler.getAuthURL
        events:
            - http:
                  path: api/get-auth-url
                  method: get
                  cors:
                      origin: '*'
                      headers:
                          - Content-Type
                          - X-Amz-Date
                          - Authorization
                          - X-Api-Key
                          - X-Amz-Security-Token
                          - X-Amz-User-Agent
                          - x-requested-with
    getAccessToken:
        handler: handler.getAccessToken
        events:
            - http:
                  path: api/token/{code}
                  method: get
                  cors:
                      origin: '*'
                      headers:
                          - Content-Type
                          - X-Amz-Date
                          - Authorization
                          - X-Api-Key
                          - X-Amz-Security-Token
                          - X-Amz-User-Agent
                          - x-requested-with
    getCalendarEvents:
        handler: handler.getCalendarEvents
        events:
            - http:
                  path: api/get-events/{access_token}
                  method: get
                  cors:
                      origin: '*'
                      headers:
                          - Content-Type
                          - X-Amz-Date
                          - Authorization
                          - X-Api-Key
                          - X-Amz-Security-Token
                          - X-Amz-User-Agent
                          - x-requested-with

resources:
    Resources:
        GatewayResponseDefault4XX:
            Type: 'AWS::ApiGateway::GatewayResponse'
            Properties:
                ResponseParameters:
                    gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
                    gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
                ResponseType: DEFAULT_4XX
                RestApiId:
                    Ref: 'ApiGatewayRestApi'
        GatewayResponseDefault5XX:
            Type: 'AWS::ApiGateway::GatewayResponse'
            Properties:
                ResponseParameters:
                    gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
                    gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
                ResponseType: DEFAULT_5XX
                RestApiId:
                    Ref: 'ApiGatewayRestApi'
